services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "${SA_PASSWORD}"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  auth-service:
    build:
      context: ./src/services/AuthService
      dockerfile: Dockerfile
    ports:
      - "5001:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=AuthDb;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True"
      Jwt__Secret: "${JWT_SECRET}"
      Jwt__Issuer: "digital-wallet"
      Jwt__Audience: "digital-wallet"
      Jwt__ExpirationHours: "8"
    depends_on:
      - sqlserver

  account-service:
    build:
      context: ./src/services/AccountService
      dockerfile: Dockerfile
    ports:
      - "5002:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=AccountDb;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True"
    depends_on:
      - sqlserver

  transaction-service:
    build:
      context: .
      dockerfile: src/services/TransactionService/Dockerfile
    ports:
      - "5003:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=TransactionDb;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True"
      RabbitMQ__Host: "rabbitmq"
      RabbitMQ__Username: "guest"
      RabbitMQ__Password: "${RABBITMQ_PASSWORD}"
      Redis__ConnectionString: "redis:6379,abortConnect=false,connectTimeout=10000"
    depends_on:
      - sqlserver
      - rabbitmq
      - redis

  notification-service:
    build:
      context: .
      dockerfile: src/services/NotificationService/Dockerfile
    environment:
      DOTNET_ENVIRONMENT: Development
      RabbitMQ__Host: "rabbitmq"
      RabbitMQ__Username: "guest"
      RabbitMQ__Password: "${RABBITMQ_PASSWORD}"
      Email__Host: "mailhog"
      Email__Port: "1025"
      Email__From: "noreply@digitalwallet.com"
      Email__DefaultRecipient: "user@digitalwallet.com"
    depends_on:
      - rabbitmq
      - mailhog

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASSWORD}"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"